name: mxnet-docs
channels:
- conda-forge
dependencies:
- conda
- jupyter
- matplotlib
- notebook
- pandas
- pandoc>=2.7.3
- pip
- python
- sphinx
- pip:
  - awscli
  - breathe
  - mock
  - mxnet
  - nbconvert>=5.5.0
  - nbsphinx>=0.4.2
  - notedown
  - pypandoc
  - recommonmark
  - git+https://github.com/rmk135/sphinxcontrib-disqus
