name: mxnet-docs
channels:
- conda-forge
dependencies:
- conda>=4.6.13
- pip
- python
- jupyter
- sphinx
- matplotlib
- notebook
- pip:
  # using nbconvert master until v5.5 comes out
  - git+https://github.com/jupyter/nbconvert@master
  - nbsphinx>=0.4.2
  - recommonmark
  - notedown
  - pypandoc
  - breathe
  - mock
  - awscli
